# teleop_twist_joy.yaml

teleop_node:
  ros__parameters:

    axis_linear:  # Left thumb stick vertical
      x: 3
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 5.0
    scale_angular_turbo:
      yaw: 10.0

    require_enable_button: true
    enable_button: 5  # Left shoulder button
    enable_turbo_button: 7  # Right shoulder button

    # Servo control buttons
    servo_buttons:
      eyebrow_left_up: 0    # A button
      eyebrow_left_down: 1  # B button
